import "./globals.css";

export const metadata = {
  title: "سامانه بوستان دانشگاه صنعتی شاهرود",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className={``}>
        {children}
      </body>
    </html>
  );
}
